version: '3.1'

services:
  graphql-example-back:
    restart: unless-stopped
    build: .
    container_name: graphql-example-back
    image: graphql-example-back
    ports:
      - "3030:80"
    environment:
      PORT: 3000